name: facilitator
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  dio: ^5.4.3+1
  logger: ^2.2.0
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.0
  otp_text_field: ^1.1.3
  shimmer: ^3.0.0
  accordion: ^2.6.0
  bloc: ^8.1.4
  image_picker: ^1.1.1
  dotted_border: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash_image.png"
  color: #030E4F
  min_sdk_android: 21
  adaptive_icon_background: "assets/images/app_icon_bg.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#030E4F"
  image: assets/images/splash_image.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
